# Generated by Django 6.0.2 on 2026-02-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.JSONField(default=list)),
                ('preview', models.JSONField(default=list)),
                ('averages', models.JSONField(default=dict)),
                ('equipment_distribution', models.JSONField(default=dict)),
            ],
        ),
    ]
